# Generated by Django 5.2.3 on 2025-06-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('home', 'Home Appliances'), ('gadgets', 'Gadgets')], default='gadgets', max_length=20),
        ),
    ]
